CREATE SCHEMA client;

CREATE TABLE client.activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    activity_type character varying(255),
    subject character varying(255),
    description text,
    source character varying(255),
    source_id bigint,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.activities.client_id IS 'Клиент';
COMMENT ON COLUMN client.activities.activity_type IS 'Тип активности';
COMMENT ON COLUMN client.activities.subject IS 'Тема';
COMMENT ON COLUMN client.activities.description IS 'Описание';
COMMENT ON COLUMN client.activities.source IS 'Источник';
COMMENT ON COLUMN client.activities.source_id IS 'ID источника';
COMMENT ON COLUMN client.activities.created_by IS 'Кем создано';

CREATE TABLE client.authorized_persons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    last_name character varying(100),
    first_name character varying(100),
    middle_name character varying(100),
    iin character varying(12),
    phone character varying(20),
    authority_description character varying(255),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    email character varying(200),
    verification_password character varying(255),
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_by uuid,
    full_name character varying(255),
    upload_log character varying(500)
);
COMMENT ON COLUMN client.authorized_persons.client_id IS 'Клиент-владелец';
COMMENT ON COLUMN client.authorized_persons.last_name IS 'Фамилия';
COMMENT ON COLUMN client.authorized_persons.first_name IS 'Имя';
COMMENT ON COLUMN client.authorized_persons.middle_name IS 'Отчество';
COMMENT ON COLUMN client.authorized_persons.iin IS 'ИИН';
COMMENT ON COLUMN client.authorized_persons.phone IS 'Телефон';
COMMENT ON COLUMN client.authorized_persons.authority_description IS 'Полномочия';
COMMENT ON COLUMN client.authorized_persons.email IS 'Email';
COMMENT ON COLUMN client.authorized_persons.verification_password IS 'Пароль';
COMMENT ON COLUMN client.authorized_persons.full_name IS 'ФИО поверенного';
COMMENT ON COLUMN client.authorized_persons.upload_log IS 'Лог загрузки файла';

CREATE TABLE client.bank_details (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    bank_name character varying(255),
    bik character varying(255),
    account_number character varying(255),
    iban character varying(255),
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    account_owner character varying(255)
);
COMMENT ON COLUMN client.bank_details.bank_name IS 'Банк';
COMMENT ON COLUMN client.bank_details.bik IS 'БИК';
COMMENT ON COLUMN client.bank_details.account_number IS 'Номер счета';
COMMENT ON COLUMN client.bank_details.iban IS 'IBAN';
COMMENT ON COLUMN client.bank_details.is_primary IS 'Основной счет';

CREATE TABLE client.billing_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    account_number character varying(50),
    balance numeric(38,2) DEFAULT 0,
    debt_amount numeric(38,2) DEFAULT 0,
    credit_limit numeric(38,2) DEFAULT 0,
    remaining_limit numeric(38,2) DEFAULT 0,
    credit_limit_increase_allowed boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.billing_accounts.account_number IS 'Номер лицевого счета';
COMMENT ON COLUMN client.billing_accounts.balance IS 'Баланс';
COMMENT ON COLUMN client.billing_accounts.debt_amount IS 'Задолженность';
COMMENT ON COLUMN client.billing_accounts.credit_limit IS 'Кредитный лимит';
COMMENT ON COLUMN client.billing_accounts.remaining_limit IS 'Остаток лимита';
COMMENT ON COLUMN client.billing_accounts.credit_limit_increase_allowed IS 'Доступ на увеличение лимита';

CREATE TABLE client.call_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id bigint,
    comment character varying(255),
    contact_person character varying(255),
    contact_type character varying(255),
    create_date timestamp(6) with time zone,
    executed_campaign_id bigint,
    phone_number character varying(255),
    promise_date timestamp(6) with time zone,
    reason_delay character varying(255),
    responsible character varying(255),
    result character varying(255),
    client_id bigint,
    contact_id bigint,
    contract character varying(255),
    duration bigint,
    ended_at timestamp(6) with time zone,
    language character varying(255),
    outcome character varying(255),
    started_at timestamp(6) with time zone
);

CREATE TABLE client.campaign (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection character varying(255),
    dep_id character varying(255),
    name character varying(255),
    segments jsonb,
    srv_dep_code character varying(255),
    username jsonb,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.campaign_sort_fields (
    campaign_id bigint NOT NULL,
    field character varying(255),
    value character varying(255),
    CONSTRAINT campaign_sort_fields_value_check CHECK (((value)::text = ANY ((ARRAY['ASC'::character varying, 'DESC'::character varying, 'ASC_ALPHA'::character varying, 'DESC_ALPHA'::character varying])::text[])))
);

CREATE TABLE client.campaign_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aim character varying(100),
    auto_closed boolean,
    collection character varying(255),
    comment character varying(255),
    contract_number character varying(255),
    dep_id character varying(255),
    expiration_date timestamp(6) with time zone,
    is_active boolean,
    is_reactivate boolean,
    is_worked boolean,
    last_action_date timestamp(6) with time zone,
    priority integer,
    reactivation_datetime timestamp(6) with time zone,
    srv_dep_code character varying(255),
    stage_of_task character varying(255),
    status character varying(255),
    task_completion_date timestamp(6) with time zone,
    task_number character varying(255),
    task_seq bigint,
    type character varying(255),
    user_name character varying(255),
    client_id bigint NOT NULL,
    manager_id bigint,
    schedule_campaign_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.campaign_task_history (
    id uuid NOT NULL,
    aim character varying(100),
    auto_closed boolean,
    campaign_task_id bigint NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    changed_by character varying(100),
    collection character varying(255),
    comment character varying(255),
    contract_number character varying(255),
    created_at timestamp(6) with time zone,
    created_by character varying(255),
    deleted_at timestamp(6) with time zone,
    dep_id character varying(255),
    expiration_date timestamp(6) with time zone,
    is_active boolean,
    is_reactivate boolean,
    is_worked boolean,
    last_action_date timestamp(6) with time zone,
    operation character varying(10) NOT NULL,
    priority integer,
    reactivation_datetime timestamp(6) with time zone,
    srv_dep_code character varying(255),
    stage_of_task character varying(255),
    status character varying(255),
    task_completion_date timestamp(6) with time zone,
    task_number character varying(255),
    task_seq bigint,
    type character varying(255),
    updated_at timestamp(6) with time zone,
    updated_by character varying(255),
    user_name character varying(255),
    client_id bigint,
    manager_id bigint,
    schedule_campaign_id bigint
);

CREATE TABLE client.channel (
    id bigint NOT NULL,
    manager boolean,
    robot boolean,
    sms boolean,
    whatsapp boolean
);

CREATE TABLE client.client_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    address_type_id bigint,
    city_region_id bigint,
    full_address text,
    postal_code character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    actual_address character varying(255),
    legal_address character varying(255)
);
COMMENT ON COLUMN client.client_addresses.address_type_id IS 'Юридический, фактический, для корреспонденции';
COMMENT ON COLUMN client.client_addresses.city_region_id IS 'Город/регион';
COMMENT ON COLUMN client.client_addresses.full_address IS 'Полный адрес';
COMMENT ON COLUMN client.client_addresses.postal_code IS 'Почтовый индекс';

CREATE TABLE client.client_contact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    contact_type_id bigint,
    value character varying(300),
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_contact.client_id IS 'Клиент';
COMMENT ON COLUMN client.client_contact.contact_type_id IS 'Тип контакта';
COMMENT ON COLUMN client.client_contact.value IS 'Значение контакта';
COMMENT ON COLUMN client.client_contact.is_primary IS 'Основной контакт';

CREATE TABLE client.client_id_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    document_type_id bigint,
    document_number character varying(50),
    issued_by character varying(300),
    issue_date date,
    expiry_date date,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_id_documents.document_type_id IS 'Тип документа: паспорт, УДЛ';
COMMENT ON COLUMN client.client_id_documents.document_number IS 'Номер документа';
COMMENT ON COLUMN client.client_id_documents.issued_by IS 'Кем выдан';
COMMENT ON COLUMN client.client_id_documents.issue_date IS 'Дата выдачи';
COMMENT ON COLUMN client.client_id_documents.expiry_date IS 'Срок действия';

CREATE TABLE client.client_phone_numbers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    phone_number character varying(255),
    brand_id bigint,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_phone_numbers.phone_number IS 'Номер телефона';
COMMENT ON COLUMN client.client_phone_numbers.brand_id IS 'Бренд: Актив / Кселл';
COMMENT ON COLUMN client.client_phone_numbers.is_active IS 'Активен';

CREATE TABLE client.client_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    product_id bigint,
    activated_at timestamp without time zone,
    deactivated_at timestamp without time zone,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    name character varying(255)
);
COMMENT ON COLUMN client.client_products.activated_at IS 'Дата активации';
COMMENT ON COLUMN client.client_products.deactivated_at IS 'Дата деактивации';

CREATE TABLE client.client_requirement_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id bigint,
    file_name character varying(255),
    file_path character varying(255),
    file_size bigint,
    uploaded_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_requirement_attachments.requirement_id IS 'Требование';
COMMENT ON COLUMN client.client_requirement_attachments.file_name IS 'Имя файла';
COMMENT ON COLUMN client.client_requirement_attachments.file_path IS 'Путь к файлу';
COMMENT ON COLUMN client.client_requirement_attachments.file_size IS 'Размер файла, байт';
COMMENT ON COLUMN client.client_requirement_attachments.uploaded_at IS 'Дата загрузки';

CREATE TABLE client.client_requirements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    description text,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_requirements.client_id IS 'Клиент';
COMMENT ON COLUMN client.client_requirements.description IS 'Текст требования (ручной ввод)';
COMMENT ON COLUMN client.client_requirements.created_by IS 'Кем создано';

CREATE TABLE client.client_restrictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    restriction_type_id bigint,
    description character varying(255),
    is_active boolean DEFAULT true,
    start_date timestamp without time zone DEFAULT now(),
    end_date timestamp without time zone,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.client_restrictions.client_id IS 'Клиент';
COMMENT ON COLUMN client.client_restrictions.restriction_type_id IS 'Тип: стоп-лист, конфликты по продуктам, задолженность';
COMMENT ON COLUMN client.client_restrictions.description IS 'Описание ограничения';
COMMENT ON COLUMN client.client_restrictions.start_date IS 'Дата начала ограничения';
COMMENT ON COLUMN client.client_restrictions.end_date IS 'Дата окончания ограничения';

CREATE TABLE client.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_type_id bigint,
    residency_id bigint,
    language_id bigint,
    city_region_id bigint,
    vip_status_id bigint,
    code_word character varying(100),
    credit_limit_increase_allowed boolean DEFAULT false,
    current_balance numeric(38,2),
    charged_amount numeric(38,2),
    remaining_balance numeric(38,2),
    has_corp_cabinet boolean DEFAULT false,
    has_mobile_app boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    status character varying(50),
    bin_iin character varying(12),
    is_deleted boolean DEFAULT false NOT NULL
);
COMMENT ON COLUMN client.clients.client_type_id IS 'Тип клиента';
COMMENT ON COLUMN client.clients.residency_id IS 'Резидентство';
COMMENT ON COLUMN client.clients.language_id IS 'Язык обслуживания';
COMMENT ON COLUMN client.clients.city_region_id IS 'Город/Регион';
COMMENT ON COLUMN client.clients.vip_status_id IS 'VIP статус';
COMMENT ON COLUMN client.clients.code_word IS 'Кодовое слово';
COMMENT ON COLUMN client.clients.credit_limit_increase_allowed IS 'Доступ на увеличение кредитного лимита';
COMMENT ON COLUMN client.clients.current_balance IS 'Текущий баланс';
COMMENT ON COLUMN client.clients.charged_amount IS 'Начислено';
COMMENT ON COLUMN client.clients.remaining_balance IS 'Остаток';
COMMENT ON COLUMN client.clients.has_corp_cabinet IS 'Наличие корп. кабинета';
COMMENT ON COLUMN client.clients.has_mobile_app IS 'Наличие мобильного приложения';
COMMENT ON COLUMN client.clients.status IS 'Статус';
COMMENT ON COLUMN client.clients.bin_iin IS 'БИН/ИИН';

CREATE TABLE client.clients_b2b (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    bin_iin character varying(12),
    company_name character varying(300),
    logo_url character varying(500),
    segment_id bigint,
    industry_id bigint,
    category_id bigint,
    legal_form_id bigint,
    department_id bigint,
    acquisition_employee_id bigint,
    retention_employee_id bigint,
    acquisition_head_id bigint,
    retention_head_id bigint,
    payment_terms character varying(200),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    contact_person_full_name character varying(255),
    contact_person_position character varying(255),
    email character varying(255),
    rnn character varying(12),
    vat_certificate character varying(100),
    economy_sector character varying(10)
);
COMMENT ON COLUMN client.clients_b2b.client_id IS 'Связь 1:1 с базовой карточкой';
COMMENT ON COLUMN client.clients_b2b.bin_iin IS 'БИН/ИИН';
COMMENT ON COLUMN client.clients_b2b.company_name IS 'Наименование компании';
COMMENT ON COLUMN client.clients_b2b.logo_url IS 'Логотип компании';
COMMENT ON COLUMN client.clients_b2b.segment_id IS 'Сегмент';
COMMENT ON COLUMN client.clients_b2b.industry_id IS 'Индустрия';
COMMENT ON COLUMN client.clients_b2b.category_id IS 'Категория ABC';
COMMENT ON COLUMN client.clients_b2b.legal_form_id IS 'ОПФ';
COMMENT ON COLUMN client.clients_b2b.department_id IS 'Направление/Отдел';
COMMENT ON COLUMN client.clients_b2b.acquisition_employee_id IS 'Ответственный Acquisition';
COMMENT ON COLUMN client.clients_b2b.retention_employee_id IS 'Ответственный Retention';
COMMENT ON COLUMN client.clients_b2b.acquisition_head_id IS 'Руководитель Acquisition';
COMMENT ON COLUMN client.clients_b2b.retention_head_id IS 'Руководитель Retention';
COMMENT ON COLUMN client.clients_b2b.payment_terms IS 'Сроки оплаты';
COMMENT ON COLUMN client.clients_b2b.contact_person_full_name IS 'Контактное лицо';
COMMENT ON COLUMN client.clients_b2b.contact_person_position IS 'Должность контактного лица';
COMMENT ON COLUMN client.clients_b2b.email IS 'Email';
COMMENT ON COLUMN client.clients_b2b.rnn IS 'РНН';
COMMENT ON COLUMN client.clients_b2b.vat_certificate IS 'Свидетельство НДС';
COMMENT ON COLUMN client.clients_b2b.economy_sector IS 'Сектор экономики';

CREATE TABLE client.clients_b2c (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    iin character varying(12),
    last_name character varying(100),
    first_name character varying(100),
    middle_name character varying(100),
    gender_id bigint,
    date_of_birth date,
    password_hash character varying(255),
    income_amount numeric(18,2),
    income_source_id bigint,
    marital_status_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    phone_b2c character varying(20),
    email character varying(255),
    language character varying(255),
    residency character varying(255),
    secret_word character varying(255)
);
COMMENT ON COLUMN client.clients_b2c.client_id IS 'Связь 1:1 с базовой карточкой';
COMMENT ON COLUMN client.clients_b2c.iin IS 'ИИН';
COMMENT ON COLUMN client.clients_b2c.last_name IS 'Фамилия';
COMMENT ON COLUMN client.clients_b2c.first_name IS 'Имя';
COMMENT ON COLUMN client.clients_b2c.middle_name IS 'Отчество';
COMMENT ON COLUMN client.clients_b2c.gender_id IS 'Пол';
COMMENT ON COLUMN client.clients_b2c.date_of_birth IS 'Дата рождения';
COMMENT ON COLUMN client.clients_b2c.password_hash IS 'Пароль';
COMMENT ON COLUMN client.clients_b2c.income_amount IS 'Сумма дохода';
COMMENT ON COLUMN client.clients_b2c.income_source_id IS 'Источник дохода';
COMMENT ON COLUMN client.clients_b2c.marital_status_id IS 'Семейное положение';

CREATE TABLE client.communicate_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal character varying(255),
    call_type character varying(255),
    channel character varying(255),
    comment character varying(255),
    contact_value character varying(255),
    create_date timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by uuid,
    date timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    delivered_at timestamp(6) with time zone,
    direction character varying(255),
    message_type character varying(255),
    promise_date timestamp(6) with time zone,
    receiver_fio character varying(255),
    responsible character varying(255),
    result character varying(255),
    status character varying(255),
    subject character varying(255),
    task_number character varying(255),
    topic character varying(255),
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    user_id uuid,
    client_id bigint NOT NULL,
    contact_id bigint,
    end_date timestamp(6) with time zone,
    start_date timestamp(6) with time zone,
    client_contact_id bigint,
    contract_id bigint
);

CREATE TABLE client.communication_contact_center (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    callback_date date,
    callback_purpose character varying(255),
    callback_time time(6) without time zone,
    channel character varying(255),
    client_id bigint,
    comment text,
    date timestamp(6) with time zone NOT NULL,
    result character varying(255),
    theme character varying(255),
    user_fio character varying(255),
    user_id bigint
);

CREATE TABLE client.communications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    action_link text,
    channel character varying(50),
    communication_date timestamp(6) with time zone,
    communication_type character varying(50),
    communications_group character varying(20),
    description text,
    priority character varying(20),
    record_url text,
    result text,
    status character varying(30),
    banking_product_id bigint,
    client_id bigint,
    manager_id uuid
);

CREATE TABLE client.contact_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint,
    address_type_id bigint,
    city_region_id bigint,
    full_address text,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contact_addresses.address_type_id IS 'Тип адреса';
COMMENT ON COLUMN client.contact_addresses.city_region_id IS 'Город/регион';
COMMENT ON COLUMN client.contact_addresses.full_address IS 'Полный адрес';

CREATE TABLE client.contact_careers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint,
    company_name character varying(255),
    "position" character varying(255),
    start_date date,
    end_date date,
    is_current boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contact_careers.company_name IS 'Название компании';
COMMENT ON COLUMN client.contact_careers.start_date IS 'Дата начала';
COMMENT ON COLUMN client.contact_careers.end_date IS 'Дата окончания';
COMMENT ON COLUMN client.contact_careers.is_current IS 'Текущее место работы';

COMMENT ON COLUMN client.contact_careers."position" IS 'Должность';

CREATE TABLE client.contact_contact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint,
    contact_type_id bigint,
    value character varying(300),
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contact_contact.contact_id IS 'Контактное лицо';
COMMENT ON COLUMN client.contact_contact.contact_type_id IS 'Тип контакта';
COMMENT ON COLUMN client.contact_contact.value IS 'Значение контакта';
COMMENT ON COLUMN client.contact_contact.is_primary IS 'Основной контакт';

CREATE TABLE client.contact_id_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint,
    document_type_id bigint,
    document_number character varying(255),
    issued_by character varying(255),
    expiry_date date,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contact_id_documents.document_type_id IS 'Тип документа';
COMMENT ON COLUMN client.contact_id_documents.document_number IS 'Номер документа';
COMMENT ON COLUMN client.contact_id_documents.issued_by IS 'Кем выдан';
COMMENT ON COLUMN client.contact_id_documents.expiry_date IS 'Срок действия';

CREATE TABLE client.contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    last_name character varying(255),
    first_name character varying(255),
    middle_name character varying(255),
    gender_id bigint,
    "position" character varying(255),
    residency_id bigint,
    code_word character varying(255),
    verification_password character varying(255),
    client_type_id bigint,
    role_id bigint,
    language_id bigint,
    date_of_birth date,
    do_not_disturb boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    accessibility character varying(255),
    contact_person_name character varying(255),
    contact_status character varying(50),
    contact_subtype character varying(50),
    contact_type character varying(50),
    contact_value character varying(255),
    convenient_time character varying(100),
    description character varying(255),
    is_actual boolean,
    is_primary boolean,
    marketing_consent boolean,
    organizational_unit_id bigint,
    preferred_channel boolean,
    priority integer,
    processing_consent boolean,
    relationship character varying(100),
    verification_date timestamp(6) with time zone,
    verification_status character varying(50)
);
COMMENT ON COLUMN client.contacts.client_id IS 'Клиент-владелец контакта';
COMMENT ON COLUMN client.contacts.last_name IS 'Фамилия';
COMMENT ON COLUMN client.contacts.first_name IS 'Имя';
COMMENT ON COLUMN client.contacts.middle_name IS 'Отчество';
COMMENT ON COLUMN client.contacts.gender_id IS 'Пол';
COMMENT ON COLUMN client.contacts.residency_id IS 'Резидентство';
COMMENT ON COLUMN client.contacts.code_word IS 'Кодовое слово';
COMMENT ON COLUMN client.contacts.verification_password IS 'Пароль на верификацию';
COMMENT ON COLUMN client.contacts.client_type_id IS 'Тип клиента контактного лица';
COMMENT ON COLUMN client.contacts.role_id IS 'Роль контактного лица';
COMMENT ON COLUMN client.contacts.language_id IS 'Язык обслуживания';
COMMENT ON COLUMN client.contacts.date_of_birth IS 'Дата рождения';
COMMENT ON COLUMN client.contacts.do_not_disturb IS 'Не тревожить';

COMMENT ON COLUMN client.contacts."position" IS 'Должность';

CREATE TABLE client.contract_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id bigint,
    document_type_id bigint,
    file_name character varying(255),
    file_path character varying(255),
    file_size character varying(255),
    uploaded_by bigint,
    uploaded_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contract_documents.contract_id IS 'Договор';
COMMENT ON COLUMN client.contract_documents.document_type_id IS 'Тип документа';
COMMENT ON COLUMN client.contract_documents.file_name IS 'Имя файла';
COMMENT ON COLUMN client.contract_documents.file_path IS 'Путь к файлу';
COMMENT ON COLUMN client.contract_documents.file_size IS 'Размер файла, байт';
COMMENT ON COLUMN client.contract_documents.uploaded_by IS 'Кем загружен';
COMMENT ON COLUMN client.contract_documents.uploaded_at IS 'Дата загрузки';

CREATE TABLE client.contract_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archived_at timestamp(6) with time zone,
    bin_iin character varying(12),
    borrower_name character varying(255),
    business_type character varying(100),
    client_account_code character varying(255),
    collection_status character varying(50),
    contract_end_date timestamp(6) with time zone,
    contract_number character varying(100),
    contract_state character varying(255),
    contract_status character varying(50),
    credit_amount numeric(15,2),
    credit_product_name character varying(255),
    credit_purpose character varying(255),
    credit_term_months integer,
    currency character varying(3),
    damu_guarantees boolean,
    delay_days integer,
    fine_amount numeric(15,2),
    general_agreement character varying(100),
    ifrs_portfolio_type character varying(100),
    ifrs_provision_interest numeric(15,2),
    ifrs_provision_interest_balance numeric(15,2),
    ifrs_provision_percentage numeric(5,2),
    ifrs_provision_principal numeric(15,2),
    ifrs_provision_principal_balance numeric(15,2),
    interest_debt numeric(15,2),
    interest_rate numeric(6,2),
    issue_date timestamp(6) with time zone,
    organizational_unit_id bigint,
    overdue_days_interest integer,
    overdue_days_principal integer,
    overdue_interest_debt numeric(15,2),
    overdue_principal_debt numeric(15,2),
    penalty_amount numeric(15,2),
    principal_debt numeric(15,2),
    product_code character varying(255),
    project_manager character varying(255),
    receivables_debt numeric(15,2),
    repayment_date character varying(255),
    restructuring_date timestamp(6) with time zone,
    statname character varying(255),
    client_id bigint,
    contract_id bigint,
    mark_id bigint
);

CREATE TABLE client.contract_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id bigint,
    product_id bigint,
    service_start_date date,
    service_end_date date,
    quantity integer DEFAULT 1,
    one_time_fee numeric(38,2) DEFAULT 0,
    monthly_fee numeric(38,2) DEFAULT 0,
    promotion character varying(300),
    discount numeric(38,2) DEFAULT 0,
    total_amount numeric(38,2) DEFAULT 0,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contract_products.product_id IS 'Продукт';
COMMENT ON COLUMN client.contract_products.service_start_date IS 'Дата начала предоставления услуги';
COMMENT ON COLUMN client.contract_products.service_end_date IS 'Дата окончания предоставления услуги';
COMMENT ON COLUMN client.contract_products.quantity IS 'Количество';
COMMENT ON COLUMN client.contract_products.one_time_fee IS 'Стоимость ЕП (единовременная плата)';
COMMENT ON COLUMN client.contract_products.monthly_fee IS 'Стоимость АП (абонентская плата)';
COMMENT ON COLUMN client.contract_products.promotion IS 'Акция';
COMMENT ON COLUMN client.contract_products.discount IS 'Скидка, %';
COMMENT ON COLUMN client.contract_products.total_amount IS 'Общая сумма';

CREATE TABLE client.contract_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_type_id bigint,
    template_name character varying(255),
    template_file_path character varying(255),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.contract_templates.contract_type_id IS 'Тип договора';
COMMENT ON COLUMN client.contract_templates.template_name IS 'Название шаблона';
COMMENT ON COLUMN client.contract_templates.template_file_path IS 'Путь к файлу шаблона для скачивания';

CREATE TABLE client.contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    registration_number character varying(255),
    start_date date,
    end_date date,
    contract_type_id bigint,
    status_id bigint,
    responsible_kcell_id bigint,
    responsible_contact_id bigint,
    billing_account_id bigint,
    balance numeric(38,2) DEFAULT 0,
    total_amount numeric(38,2) DEFAULT 0,
    payment_form_id bigint,
    is_debtor boolean DEFAULT false,
    residual_value numeric(38,2),
    currency_id bigint,
    parent_contract_id bigint,
    is_open_incomplete boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    contract_number character varying(255)
);
COMMENT ON COLUMN client.contracts.client_id IS 'Клиент';
COMMENT ON COLUMN client.contracts.registration_number IS 'Регистрационный номер';
COMMENT ON COLUMN client.contracts.start_date IS 'Дата начала';
COMMENT ON COLUMN client.contracts.end_date IS 'Дата окончания';
COMMENT ON COLUMN client.contracts.contract_type_id IS 'Тип договора';
COMMENT ON COLUMN client.contracts.status_id IS 'Статус';
COMMENT ON COLUMN client.contracts.responsible_kcell_id IS 'Ответственный Кселл';
COMMENT ON COLUMN client.contracts.responsible_contact_id IS 'Ответственный клиента';
COMMENT ON COLUMN client.contracts.billing_account_id IS 'Лицевой счет';
COMMENT ON COLUMN client.contracts.balance IS 'Баланс';
COMMENT ON COLUMN client.contracts.total_amount IS 'Общая сумма';
COMMENT ON COLUMN client.contracts.payment_form_id IS 'Форма оплаты';
COMMENT ON COLUMN client.contracts.is_debtor IS 'Должник';
COMMENT ON COLUMN client.contracts.residual_value IS 'Остаточная стоимость';
COMMENT ON COLUMN client.contracts.currency_id IS 'Валюта';
COMMENT ON COLUMN client.contracts.parent_contract_id IS 'Родительский договор';
COMMENT ON COLUMN client.contracts.is_open_incomplete IS 'Открытый незавершенный';

CREATE TABLE client.credit_history_individual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(15,2),
    close_date timestamp(6) with time zone,
    credit_type character varying(100),
    currency character varying(3),
    interest_rate numeric(5,2),
    issue_date timestamp(6) with time zone,
    status character varying(50),
    term_months integer,
    individual_client_id bigint
);

CREATE TABLE client.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    document_type_id bigint,
    category character varying(20),
    status character varying(255) DEFAULT 'active'::character varying,
    file_name character varying(255),
    file_path character varying(255),
    file_size bigint,
    uploaded_by bigint,
    uploaded_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    s3_key character varying(1000),
    file_hash character varying(64),
    enrichment_status character varying(50) DEFAULT 'stored'::character varying,
    retry_count integer DEFAULT 0 NOT NULL,
    last_retry_at timestamp with time zone,
    extracted_fields jsonb,
    product_code character varying(255),
    doc_type character varying(255)
);
COMMENT ON COLUMN client.documents.client_id IS 'Клиент';
COMMENT ON COLUMN client.documents.document_type_id IS 'Тип документа';
COMMENT ON COLUMN client.documents.category IS 'Категория';
COMMENT ON COLUMN client.documents.status IS 'Статус';
COMMENT ON COLUMN client.documents.file_name IS 'Имя файла';
COMMENT ON COLUMN client.documents.file_path IS 'Путь к файлу';
COMMENT ON COLUMN client.documents.file_size IS 'Размер файла';
COMMENT ON COLUMN client.documents.uploaded_by IS 'Кем загружен';
COMMENT ON COLUMN client.documents.uploaded_at IS 'Дата загрузки';

CREATE TABLE client.employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name character varying(100),
    last_name character varying(100),
    middle_name character varying(100),
    "position" character varying(255),
    department_id bigint,
    supervisor_id bigint,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.employees.first_name IS 'Имя';
COMMENT ON COLUMN client.employees.last_name IS 'Фамилия';
COMMENT ON COLUMN client.employees.middle_name IS 'Отчество';
COMMENT ON COLUMN client.employees.department_id IS 'Направление/Отдел';
COMMENT ON COLUMN client.employees.supervisor_id IS 'Начальник';

COMMENT ON COLUMN client.employees."position" IS 'Должность';

CREATE TABLE client.governing_bodies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name character varying(255),
    end_date timestamp(6) with time zone,
    governing_body_type character varying(100),
    is_actual boolean,
    role_position character varying(100),
    start_date timestamp(6) with time zone,
    client_id bigint
);

CREATE TABLE client.identity_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code character varying(50),
    document_number character varying(50),
    document_scan_url character varying(255),
    document_series character varying(50),
    document_type character varying(255),
    expiry_date timestamp(6) with time zone,
    is_archived boolean,
    is_primary boolean,
    issue_date timestamp(6) with time zone,
    issued_by character varying(255),
    organizational_unit_id bigint,
    client_id bigint
);

CREATE TABLE client.individual_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bankrot_fl boolean,
    birth_date character varying(255),
    birth_place character varying(255),
    children_count integer,
    citizenship character varying(50),
    first_name character varying(100),
    gender character varying(10),
    iin character varying(12),
    iin_status character varying(50),
    last_name character varying(100),
    marital_status character varying(50),
    middle_name character varying(100),
    photo_url character varying(50),
    resident boolean,
    client_id bigint
);

CREATE TABLE client.lead_appeals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign character varying(255),
    category character varying(50),
    channel character varying(255),
    client_id bigint,
    client_type character varying(100),
    contact_id bigint NOT NULL,
    created_date timestamp(6) with time zone NOT NULL,
    deleted boolean,
    fio character varying(255),
    manager_id bigint,
    product character varying(255),
    status character varying(50) NOT NULL,
    theme character varying(255),
    type character varying(50),
    unit_id bigint,
    updated_date timestamp(6) with time zone,
    comment character varying(1000),
    file_id character varying(100)
);
COMMENT ON COLUMN client.lead_appeals.campaign IS 'Кампания';
COMMENT ON COLUMN client.lead_appeals.category IS 'Категория';
COMMENT ON COLUMN client.lead_appeals.channel IS 'Канал';
COMMENT ON COLUMN client.lead_appeals.client_id IS 'ID клиента';
COMMENT ON COLUMN client.lead_appeals.client_type IS 'Тип клиента';
COMMENT ON COLUMN client.lead_appeals.contact_id IS 'ID контакта';
COMMENT ON COLUMN client.lead_appeals.created_date IS 'Дата создания';
COMMENT ON COLUMN client.lead_appeals.deleted IS 'Удален';
COMMENT ON COLUMN client.lead_appeals.fio IS 'ФИО';
COMMENT ON COLUMN client.lead_appeals.manager_id IS 'ID менеджера';
COMMENT ON COLUMN client.lead_appeals.product IS 'Продукт';
COMMENT ON COLUMN client.lead_appeals.status IS 'Статус';
COMMENT ON COLUMN client.lead_appeals.theme IS 'Тема';
COMMENT ON COLUMN client.lead_appeals.type IS 'Тип';
COMMENT ON COLUMN client.lead_appeals.unit_id IS 'ID подразделения';
COMMENT ON COLUMN client.lead_appeals.updated_date IS 'Дата обновления';

CREATE TABLE client.lead_appeals_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment character varying(250),
    created_date timestamp(6) with time zone NOT NULL,
    file_id character varying(100),
    lead_appeals_id bigint NOT NULL,
    manager_id bigint,
    status character varying(50) NOT NULL,
    type character varying(50)
);

CREATE TABLE client.managers_user (
    id uuid NOT NULL,
    email character varying(100),
    full_name character varying(255),
    organizational_unit_id bigint,
    phone character varying(20),
    "position" character varying(100),
    role character varying(50),
    status character varying(30)
);

CREATE TABLE client.marketing_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel character varying(100),
    created_date timestamp(6) with time zone NOT NULL,
    ended_date timestamp(6) with time zone,
    expiration_date timestamp(6) with time zone NOT NULL,
    lead_appeals_id bigint NOT NULL,
    manager_id bigint,
    type character varying(100),
    status character varying(255)
);

CREATE TABLE client.marks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255),
    name character varying(255),
    type character varying(255),
    parent_id bigint
);

CREATE TABLE client.payment_history (
    tra_id bigint NOT NULL,
    amount numeric(15,2),
    channel character varying(255),
    contract_number character varying(255),
    currency character varying(255),
    operation_code character varying(255),
    operation_name character varying(255),
    organizational_unit_id bigint,
    payment_date date,
    client_id bigint,
    contract_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.payment_schedule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commission_amount numeric(15,2),
    interest_amount numeric(15,2),
    payment_date timestamp(6) with time zone,
    principal_amount numeric(15,2),
    remaining_balance numeric(15,2),
    total_amount numeric(15,2),
    contract_id bigint
);

CREATE TABLE client.poa_change_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poa_id bigint,
    field_changed character varying(255),
    old_value character varying(255),
    new_value character varying(255),
    changed_by bigint,
    changed_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.poa_change_history.poa_id IS 'Доверенность';
COMMENT ON COLUMN client.poa_change_history.field_changed IS 'Измененное поле';
COMMENT ON COLUMN client.poa_change_history.old_value IS 'Старое значение';
COMMENT ON COLUMN client.poa_change_history.new_value IS 'Новое значение';
COMMENT ON COLUMN client.poa_change_history.changed_by IS 'Кем изменено';
COMMENT ON COLUMN client.poa_change_history.changed_at IS 'Дата изменения';

CREATE TABLE client.powers_of_attorney (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    contact_id bigint,
    poa_type_id bigint,
    document_type_id bigint,
    start_date date,
    end_date date,
    status character varying(255) DEFAULT 'active'::character varying,
    file_name character varying(255),
    file_path character varying(255),
    expiry_notification_sent boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    authorized_person_id bigint,
    validity_period character varying(255)
);
COMMENT ON COLUMN client.powers_of_attorney.client_id IS 'Клиент';
COMMENT ON COLUMN client.powers_of_attorney.contact_id IS 'Контактное лицо (фильтр по контактам клиента)';
COMMENT ON COLUMN client.powers_of_attorney.poa_type_id IS 'Вид доверенности';
COMMENT ON COLUMN client.powers_of_attorney.document_type_id IS 'Тип документа';
COMMENT ON COLUMN client.powers_of_attorney.start_date IS 'Дата начала';
COMMENT ON COLUMN client.powers_of_attorney.end_date IS 'Дата окончания';
COMMENT ON COLUMN client.powers_of_attorney.status IS 'Статус документа';
COMMENT ON COLUMN client.powers_of_attorney.file_name IS 'Имя файла';
COMMENT ON COLUMN client.powers_of_attorney.file_path IS 'Путь к файлу';
COMMENT ON COLUMN client.powers_of_attorney.expiry_notification_sent IS 'Уведомление об истечении';
COMMENT ON COLUMN client.powers_of_attorney.authorized_person_id IS 'Уполномоченное лицо';
COMMENT ON COLUMN client.powers_of_attorney.validity_period IS 'Период действия';

CREATE TABLE client.processing_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment character varying(255),
    next_processing_date timestamp(6) with time zone,
    processing_comment character varying(255),
    processing_date timestamp(6) with time zone,
    processing_result character varying(500),
    promise_date timestamp(6) with time zone,
    responsible character varying(255),
    task_number character varying(255),
    client_id bigint NOT NULL,
    contract_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.products_services (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255),
    description character varying(255),
    product_type character varying(255),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.products_services.name IS 'Наименование продукта/услуги';
COMMENT ON COLUMN client.products_services.description IS 'Описание';
COMMENT ON COLUMN client.products_services.product_type IS 'Тип: продукт, услуга, устройство';

CREATE TABLE client.ref_address_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_address_types.code IS 'Юридический, фактический, для корреспонденции';

CREATE TABLE client.ref_brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_brands.code IS 'Актив, Кселл';

CREATE TABLE client.ref_cities_regions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255),
    region character varying(255),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_cities_regions.name IS 'Город';
COMMENT ON COLUMN client.ref_cities_regions.region IS 'Регион';

CREATE TABLE client.ref_client_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_client_categories.code IS 'Категория ABC';

CREATE TABLE client.ref_client_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_client_types.code IS 'Потенциальный, Бывший, B2B, B2C, Партнёр, Агент';

CREATE TABLE client.ref_contact_info_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_contact_info_types.code IS 'phone, email, whatsapp, telegram и др.';

CREATE TABLE client.ref_contact_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_contact_roles.name IS 'Роль контактного лица';

CREATE TABLE client.ref_contract_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_contract_statuses.code IS 'Подготовка, Действующий, Расторгнут';

CREATE TABLE client.ref_contract_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_contract_types.code IS 'Договор, Спецификация, ДС';

CREATE TABLE client.ref_currencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_currencies.code IS 'KZT, USD, EUR и др.';

CREATE TABLE client.ref_departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    parent_id bigint,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_departments.parent_id IS 'Иерархия: Направление > Сектор > Отдел';

CREATE TABLE client.ref_document_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_document_types.name IS 'Тип документа в архиве';

CREATE TABLE client.ref_genders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);

CREATE TABLE client.ref_id_document_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_id_document_types.code IS 'Паспорт, УДЛ и др.';

CREATE TABLE client.ref_income_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_income_sources.name IS 'Источник дохода';

CREATE TABLE client.ref_industries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_industries.name IS 'Индустрия';

CREATE TABLE client.ref_languages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255),
    name character varying(255),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_languages.name IS 'Язык обслуживания';

CREATE TABLE client.ref_legal_forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_legal_forms.name IS 'ОПФ — организационно-правовая форма';

CREATE TABLE client.ref_marital_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_marital_statuses.name IS 'Семейное положение';

CREATE TABLE client.ref_payment_forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_payment_forms.name IS 'Форма оплаты: кредит и т.д.';

CREATE TABLE client.ref_poa_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_poa_types.name IS 'Вид доверенности';

CREATE TABLE client.ref_residencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255),
    name character varying(255),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_residencies.name IS 'Резидент / Нерезидент';

CREATE TABLE client.ref_restriction_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(20),
    name character varying(100) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_restriction_types.code IS 'Стоп-лист, конфликт по продуктам, задолженность';

CREATE TABLE client.ref_segments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100),
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_segments.name IS 'Сегмент клиента';

CREATE TABLE client.ref_vip_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255),
    name character varying(255) NOT NULL,
    name_en character varying,
    name_kz character varying
);
COMMENT ON COLUMN client.ref_vip_statuses.code IS 'TOP / VIP / не заполнено';

CREATE TABLE client.related_contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id bigint,
    related_contract_id bigint,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.related_contracts.contract_id IS 'Договор';
COMMENT ON COLUMN client.related_contracts.related_contract_id IS 'Связанный договор';

CREATE TABLE client.result_managers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment character varying(255),
    create_date timestamp(6) without time zone,
    fio character varying(255),
    next_processing_date timestamp(6) with time zone,
    promise_date timestamp(6) with time zone,
    result character varying(255),
    result_date timestamp(6) with time zone,
    user_name character varying(255),
    client_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.schedule_campaign (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assign_manager_user_id bigint,
    channel character varying(255),
    collection character varying(255),
    dep_id character varying(255),
    end_time timestamp(6) with time zone,
    is_active boolean,
    last_activate_date timestamp(6) with time zone,
    name character varying(255),
    srv_dep_code character varying(255),
    start_time timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.schedule_campaign_days_of_week (
    schedule_campaign_id bigint NOT NULL,
    days_of_week character varying(255)
);

CREATE TABLE client.schedule_campaign_robot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(255),
    robot_id bigint,
    robot_name character varying(255),
    schedule_campaign_settings_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.schedule_campaign_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot_id bigint,
    skill_group_id bigint,
    user_id bigint,
    campaign_id bigint,
    schedule_campaign_id bigint,
    schedule_campaign_user_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.schedule_campaign_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio text,
    skill_group_id bigint,
    source character varying(255),
    user_id bigint,
    username text,
    schedule_campaign_settings_id bigint,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.segment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection character varying(255),
    conditions jsonb,
    dep_id character varying(255),
    description character varying(255),
    edit_date timestamp(6) with time zone,
    name character varying(255),
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    campaign_id bigint
);

CREATE TABLE client.skill_group (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection character varying(255),
    dep_id character varying(255),
    name character varying(255),
    srv_dep_code character varying(255),
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

CREATE TABLE client.skill_group_users (
    skill_group_id bigint NOT NULL,
    fio character varying(255),
    user_id bigint,
    username character varying(255)
);

CREATE TABLE client.special_tariff_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    product_id bigint,
    description text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.special_tariff_plans.product_id IS 'Доступная услуга/устройство';
COMMENT ON COLUMN client.special_tariff_plans.description IS 'Описание спец. условий';

CREATE TABLE client.subsidiaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_client_id bigint,
    company_name character varying(255),
    bin character varying(255),
    city_region_id bigint,
    created_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.subsidiaries.parent_client_id IS 'Родительская компания';
COMMENT ON COLUMN client.subsidiaries.company_name IS 'Дочерняя компания';
COMMENT ON COLUMN client.subsidiaries.bin IS 'БИН филиала';
COMMENT ON COLUMN client.subsidiaries.city_region_id IS 'Город';

CREATE TABLE client.task_match (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    company_client_count integer,
    date timestamp(6) with time zone,
    is_matched boolean,
    name character varying(255),
    task_client_count integer,
    user_name character varying(255)
);

CREATE TABLE client.task_match_client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    task_match_id bigint
);

CREATE TABLE client.tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint,
    external_ticket_id character varying(255),
    status character varying(255),
    subject character varying(255),
    description text,
    assigned_to bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
COMMENT ON COLUMN client.tickets.client_id IS 'Клиент';
COMMENT ON COLUMN client.tickets.external_ticket_id IS 'ID тикета SAO';
COMMENT ON COLUMN client.tickets.status IS 'Статус';
COMMENT ON COLUMN client.tickets.subject IS 'Тема';
COMMENT ON COLUMN client.tickets.description IS 'Описание';
COMMENT ON COLUMN client.tickets.assigned_to IS 'Назначено на';

CREATE TABLE client.upload_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name character varying(255),
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    updated_by uuid
);

ALTER TABLE ONLY client.billing_accounts
    ADD CONSTRAINT billing_accounts_account_number_key UNIQUE (account_number);

ALTER TABLE ONLY client.campaign_task_history
    ADD CONSTRAINT campaign_task_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.channel
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_bin_iin_key UNIQUE (bin_iin);

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_iin_key UNIQUE (iin);

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_registration_number_key UNIQUE (registration_number);

ALTER TABLE ONLY client.managers_user
    ADD CONSTRAINT managers_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.payment_history
    ADD CONSTRAINT payment_history_pkey PRIMARY KEY (tra_id);

ALTER TABLE ONLY client.products_services
    ADD CONSTRAINT products_services_name_key UNIQUE (name);

ALTER TABLE ONLY client.ref_address_types
    ADD CONSTRAINT ref_address_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_brands
    ADD CONSTRAINT ref_brands_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_client_categories
    ADD CONSTRAINT ref_client_categories_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_client_types
    ADD CONSTRAINT ref_client_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_contact_info_types
    ADD CONSTRAINT ref_contact_info_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_contact_roles
    ADD CONSTRAINT ref_contact_roles_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_contract_statuses
    ADD CONSTRAINT ref_contract_statuses_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_contract_types
    ADD CONSTRAINT ref_contract_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_currencies
    ADD CONSTRAINT ref_currencies_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_document_types
    ADD CONSTRAINT ref_document_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_genders
    ADD CONSTRAINT ref_genders_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_id_document_types
    ADD CONSTRAINT ref_id_document_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_languages
    ADD CONSTRAINT ref_languages_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_legal_forms
    ADD CONSTRAINT ref_legal_forms_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_marital_statuses
    ADD CONSTRAINT ref_marital_statuses_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_payment_forms
    ADD CONSTRAINT ref_payment_forms_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_poa_types
    ADD CONSTRAINT ref_poa_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_residencies
    ADD CONSTRAINT ref_residencies_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_restriction_types
    ADD CONSTRAINT ref_restriction_types_code_key UNIQUE (code);

ALTER TABLE ONLY client.ref_vip_statuses
    ADD CONSTRAINT ref_vip_statuses_code_key UNIQUE (code);

ALTER TABLE ONLY client.schedule_campaign_settings
    ADD CONSTRAINT uk133oul1wtkrawjp8ngja88tgg UNIQUE (schedule_campaign_id);

ALTER TABLE ONLY client.schedule_campaign_settings
    ADD CONSTRAINT ukhc27r5pqsiqffakqyur2u6o1o UNIQUE (schedule_campaign_user_id);

ALTER TABLE ONLY client.individual_clients
    ADD CONSTRAINT uklcrpn68xverashg7fui1qjb0a UNIQUE (client_id);

ALTER TABLE ONLY client.schedule_campaign_user
    ADD CONSTRAINT ukt1ocxd70khktcm398b0csuc9a UNIQUE (schedule_campaign_settings_id);

ALTER TABLE ONLY client.authorized_persons
    ADD CONSTRAINT uq_authorized_persons_client_fullname UNIQUE (client_id, full_name);

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT uq_clients_bin_iin UNIQUE (bin_iin);

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT uq_poa_person_dates UNIQUE (authorized_person_id, start_date, end_date);

CREATE UNIQUE INDEX client_addresses_client_id_address_type_id_idx ON client.client_addresses USING btree (client_id, address_type_id);

CREATE INDEX contact_careers_contact_id_start_date_idx ON client.contact_careers USING btree (contact_id, start_date);

CREATE INDEX idx_communications_client ON client.communications USING btree (client_id);

CREATE INDEX idx_communications_date ON client.communications USING btree (communication_date);

CREATE INDEX idx_communications_type ON client.communications USING btree (communication_type);

CREATE INDEX idx_contacts_client ON client.contacts USING btree (client_id);

CREATE INDEX idx_contracts_client ON client.contracts USING btree (client_id);

CREATE INDEX idx_credit_history_individual ON client.credit_history_individual USING btree (individual_client_id);

CREATE INDEX idx_individual_iin ON client.individual_clients USING btree (iin);

CREATE UNIQUE INDEX related_contracts_contract_id_related_contract_id_idx ON client.related_contracts USING btree (contract_id, related_contract_id);

CREATE UNIQUE INDEX special_tariff_plans_client_id_product_id_idx ON client.special_tariff_plans USING btree (client_id, product_id);

ALTER TABLE ONLY client.activities
    ADD CONSTRAINT activities_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.authorized_persons
    ADD CONSTRAINT authorized_persons_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.bank_details
    ADD CONSTRAINT bank_details_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.billing_accounts
    ADD CONSTRAINT billing_accounts_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_addresses
    ADD CONSTRAINT client_addresses_address_type_id_fkey FOREIGN KEY (address_type_id) REFERENCES client.ref_address_types(id) DEFERRABLE;

ALTER TABLE ONLY client.client_addresses
    ADD CONSTRAINT client_addresses_city_region_id_fkey FOREIGN KEY (city_region_id) REFERENCES client.ref_cities_regions(id) DEFERRABLE;

ALTER TABLE ONLY client.client_addresses
    ADD CONSTRAINT client_addresses_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_contact
    ADD CONSTRAINT client_contact_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_contact
    ADD CONSTRAINT client_contact_contact_type_id_fkey FOREIGN KEY (contact_type_id) REFERENCES client.ref_contact_info_types(id) DEFERRABLE;

ALTER TABLE ONLY client.client_id_documents
    ADD CONSTRAINT client_id_documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_id_documents
    ADD CONSTRAINT client_id_documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES client.ref_id_document_types(id) DEFERRABLE;

ALTER TABLE ONLY client.client_phone_numbers
    ADD CONSTRAINT client_phone_numbers_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES client.ref_brands(id) DEFERRABLE;

ALTER TABLE ONLY client.client_phone_numbers
    ADD CONSTRAINT client_phone_numbers_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_products
    ADD CONSTRAINT client_products_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_products
    ADD CONSTRAINT client_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES client.products_services(id) DEFERRABLE;

ALTER TABLE ONLY client.client_requirement_attachments
    ADD CONSTRAINT client_requirement_attachments_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES client.client_requirements(id) DEFERRABLE;

ALTER TABLE ONLY client.client_requirements
    ADD CONSTRAINT client_requirements_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_restrictions
    ADD CONSTRAINT client_restrictions_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.client_restrictions
    ADD CONSTRAINT client_restrictions_restriction_type_id_fkey FOREIGN KEY (restriction_type_id) REFERENCES client.ref_restriction_types(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_category_id_fkey FOREIGN KEY (category_id) REFERENCES client.ref_client_categories(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_department_id_fkey FOREIGN KEY (department_id) REFERENCES client.ref_departments(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES client.ref_industries(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_legal_form_id_fkey FOREIGN KEY (legal_form_id) REFERENCES client.ref_legal_forms(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT clients_b2b_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES client.ref_segments(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES client.ref_genders(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_income_source_id_fkey FOREIGN KEY (income_source_id) REFERENCES client.ref_income_sources(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2c
    ADD CONSTRAINT clients_b2c_marital_status_id_fkey FOREIGN KEY (marital_status_id) REFERENCES client.ref_marital_statuses(id) DEFERRABLE;

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT clients_city_region_id_fkey FOREIGN KEY (city_region_id) REFERENCES client.ref_cities_regions(id) DEFERRABLE;

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT clients_client_type_id_fkey FOREIGN KEY (client_type_id) REFERENCES client.ref_client_types(id) DEFERRABLE;

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT clients_language_id_fkey FOREIGN KEY (language_id) REFERENCES client.ref_languages(id) DEFERRABLE;

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT clients_residency_id_fkey FOREIGN KEY (residency_id) REFERENCES client.ref_residencies(id) DEFERRABLE;

ALTER TABLE ONLY client.clients
    ADD CONSTRAINT clients_vip_status_id_fkey FOREIGN KEY (vip_status_id) REFERENCES client.ref_vip_statuses(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_addresses
    ADD CONSTRAINT contact_addresses_address_type_id_fkey FOREIGN KEY (address_type_id) REFERENCES client.ref_address_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_addresses
    ADD CONSTRAINT contact_addresses_city_region_id_fkey FOREIGN KEY (city_region_id) REFERENCES client.ref_cities_regions(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_addresses
    ADD CONSTRAINT contact_addresses_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_careers
    ADD CONSTRAINT contact_careers_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_contact
    ADD CONSTRAINT contact_contact_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_contact
    ADD CONSTRAINT contact_contact_contact_type_id_fkey FOREIGN KEY (contact_type_id) REFERENCES client.ref_contact_info_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_id_documents
    ADD CONSTRAINT contact_id_documents_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.contact_id_documents
    ADD CONSTRAINT contact_id_documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES client.ref_id_document_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_client_type_id_fkey FOREIGN KEY (client_type_id) REFERENCES client.ref_client_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES client.ref_genders(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_language_id_fkey FOREIGN KEY (language_id) REFERENCES client.ref_languages(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_residency_id_fkey FOREIGN KEY (residency_id) REFERENCES client.ref_residencies(id) DEFERRABLE;

ALTER TABLE ONLY client.contacts
    ADD CONSTRAINT contacts_role_id_fkey FOREIGN KEY (role_id) REFERENCES client.ref_contact_roles(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_documents
    ADD CONSTRAINT contract_documents_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES client.contracts(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_documents
    ADD CONSTRAINT contract_documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES client.ref_document_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_products
    ADD CONSTRAINT contract_products_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES client.contracts(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_products
    ADD CONSTRAINT contract_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES client.products_services(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_templates
    ADD CONSTRAINT contract_templates_contract_type_id_fkey FOREIGN KEY (contract_type_id) REFERENCES client.ref_contract_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_billing_account_id_fkey FOREIGN KEY (billing_account_id) REFERENCES client.billing_accounts(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_contract_type_id_fkey FOREIGN KEY (contract_type_id) REFERENCES client.ref_contract_types(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES client.ref_currencies(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_parent_contract_id_fkey FOREIGN KEY (parent_contract_id) REFERENCES client.contracts(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_payment_form_id_fkey FOREIGN KEY (payment_form_id) REFERENCES client.ref_payment_forms(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_responsible_contact_id_fkey FOREIGN KEY (responsible_contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT contracts_status_id_fkey FOREIGN KEY (status_id) REFERENCES client.ref_contract_statuses(id) DEFERRABLE;

ALTER TABLE ONLY client.documents
    ADD CONSTRAINT documents_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.documents
    ADD CONSTRAINT documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES client.ref_document_types(id) DEFERRABLE;

ALTER TABLE ONLY client.employees
    ADD CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES client.ref_departments(id) DEFERRABLE;

ALTER TABLE ONLY client.employees
    ADD CONSTRAINT employees_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES client.employees(id) DEFERRABLE;

ALTER TABLE ONLY client.campaign_task_history
    ADD CONSTRAINT fk11qangtpbbxbfmvpfh5ov32uc FOREIGN KEY (manager_id) REFERENCES client.result_managers(id);

ALTER TABLE ONLY client.individual_clients
    ADD CONSTRAINT fk1p3kccmlpb6e31m12gm492fq8 FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.schedule_campaign_robot
    ADD CONSTRAINT fk1pnfb0nashiott8emnpgr3xvn FOREIGN KEY (schedule_campaign_settings_id) REFERENCES client.schedule_campaign_settings(id);

ALTER TABLE ONLY client.skill_group_users
    ADD CONSTRAINT fk1r9jg79hd089jt9r0ief3n6dg FOREIGN KEY (skill_group_id) REFERENCES client.skill_group(id);

ALTER TABLE ONLY client.communicate_result
    ADD CONSTRAINT fk49od6nqncyqfm66latj81v2kg FOREIGN KEY (client_contact_id) REFERENCES client.contacts(id);

ALTER TABLE ONLY client.governing_bodies
    ADD CONSTRAINT fk5rpstlu6t3l5r0t9kynlb5upm FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.credit_history_individual
    ADD CONSTRAINT fk6urm7drt3oy0idcuisv0y4s2d FOREIGN KEY (individual_client_id) REFERENCES client.individual_clients(id);

ALTER TABLE ONLY client.campaign_task
    ADD CONSTRAINT fk7pnv0igy3ox2hguxd9v4vhmd4 FOREIGN KEY (manager_id) REFERENCES client.result_managers(id);

ALTER TABLE ONLY client.call_result
    ADD CONSTRAINT fk80vbt3ij0bvj74i2ahvlpjjux FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.payment_history
    ADD CONSTRAINT fk8mx3tawfodklay4kcobx6urlv FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.activities
    ADD CONSTRAINT fk_activities_created_by_users FOREIGN KEY (created_by) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.client_requirements
    ADD CONSTRAINT fk_client_requirements_created_by_users FOREIGN KEY (created_by) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT fk_clients_b2b_acquisition_employee_id_users FOREIGN KEY (acquisition_employee_id) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT fk_clients_b2b_acquisition_head_id_users FOREIGN KEY (acquisition_head_id) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT fk_clients_b2b_retention_employee_id_users FOREIGN KEY (retention_employee_id) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.clients_b2b
    ADD CONSTRAINT fk_clients_b2b_retention_head_id_users FOREIGN KEY (retention_head_id) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.contract_documents
    ADD CONSTRAINT fk_contract_documents_uploaded_by_users FOREIGN KEY (uploaded_by) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.contracts
    ADD CONSTRAINT fk_contracts_responsible_kcell_id_users FOREIGN KEY (responsible_kcell_id) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.documents
    ADD CONSTRAINT fk_documents_uploaded_by_users FOREIGN KEY (uploaded_by) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.lead_appeals
    ADD CONSTRAINT fk_lead_appeals_contact FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT fk_poa_authorized_person FOREIGN KEY (authorized_person_id) REFERENCES client.authorized_persons(id) DEFERRABLE;

ALTER TABLE ONLY client.poa_change_history
    ADD CONSTRAINT fk_poa_change_history_changed_by_users FOREIGN KEY (changed_by) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.tickets
    ADD CONSTRAINT fk_tickets_assigned_to_users FOREIGN KEY (assigned_to) REFERENCES users.users(id) DEFERRABLE;

ALTER TABLE ONLY client.campaign_task
    ADD CONSTRAINT fkawufca7limuyunfej6jkjt15j FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.communications
    ADD CONSTRAINT fkaxxegsuyggu54b20j7cj2y0co FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.schedule_campaign_settings
    ADD CONSTRAINT fkbi1jgyjbuqf9ffnhov7kqtl4l FOREIGN KEY (campaign_id) REFERENCES client.campaign(id);

ALTER TABLE ONLY client.contract_history
    ADD CONSTRAINT fkceijaao8w6rl6133b8cmdqyso FOREIGN KEY (mark_id) REFERENCES client.marks(id);

ALTER TABLE ONLY client.campaign_task
    ADD CONSTRAINT fkf7otpub3x8b4kmsfbn1lpd7qh FOREIGN KEY (schedule_campaign_id) REFERENCES client.schedule_campaign(id);

ALTER TABLE ONLY client.contract_history
    ADD CONSTRAINT fkfgjftleol9vcsf04vay7chom6 FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.payment_history
    ADD CONSTRAINT fkhw5fp2iib4550q8ekp77npfle FOREIGN KEY (contract_id) REFERENCES client.contracts(id);

ALTER TABLE ONLY client.segment
    ADD CONSTRAINT fkifr26lf5gqgt69hij2xx1vt97 FOREIGN KEY (campaign_id) REFERENCES client.campaign(id);

ALTER TABLE ONLY client.task_match_client
    ADD CONSTRAINT fkih194g8b67jo2fjauor3nny4n FOREIGN KEY (task_match_id) REFERENCES client.task_match(id);

ALTER TABLE ONLY client.payment_schedule
    ADD CONSTRAINT fkj72muwe941g4jaki9gof8yol7 FOREIGN KEY (contract_id) REFERENCES client.contracts(id);

ALTER TABLE ONLY client.schedule_campaign_days_of_week
    ADD CONSTRAINT fkkjq7ss48eeyf9kgv02isu6w3o FOREIGN KEY (schedule_campaign_id) REFERENCES client.schedule_campaign(id);

ALTER TABLE ONLY client.processing_results
    ADD CONSTRAINT fkl39pqicnk0jx9p9atbfx191ua FOREIGN KEY (contract_id) REFERENCES client.contracts(id);

ALTER TABLE ONLY client.result_managers
    ADD CONSTRAINT fkm4q0w791ev49vcujh95mq29a5 FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.campaign_task_history
    ADD CONSTRAINT fkmb1ooj004ysnb35fl1cl7pyo3 FOREIGN KEY (schedule_campaign_id) REFERENCES client.schedule_campaign(id);

ALTER TABLE ONLY client.identity_documents
    ADD CONSTRAINT fkn7vhdd1jnhs5u3d09wcwvi6vg FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.communicate_result
    ADD CONSTRAINT fknh274i25bd91dsjvx2ctnulwx FOREIGN KEY (contract_id) REFERENCES client.contracts(id);

ALTER TABLE ONLY client.schedule_campaign_settings
    ADD CONSTRAINT fkoodfrf1qpsoinxv2rjvrxqjy8 FOREIGN KEY (schedule_campaign_id) REFERENCES client.schedule_campaign(id);

ALTER TABLE ONLY client.schedule_campaign_settings
    ADD CONSTRAINT fkpqsrg69dmunf23tdr605l5csc FOREIGN KEY (schedule_campaign_user_id) REFERENCES client.schedule_campaign_user(id);

ALTER TABLE ONLY client.campaign_task_history
    ADD CONSTRAINT fkqf1db8o0v7fffdstsefyjyf1o FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.marks
    ADD CONSTRAINT fkqfp5dcdhorj9kd3rbw1h4kf4l FOREIGN KEY (parent_id) REFERENCES client.marks(id);

ALTER TABLE ONLY client.processing_results
    ADD CONSTRAINT fkr7wnn0un12pri988y0wa9ack8 FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.contract_history
    ADD CONSTRAINT fkrf22gfq8wpe4qvpxyqnuv6mct FOREIGN KEY (contract_id) REFERENCES client.contracts(id);

ALTER TABLE ONLY client.campaign_sort_fields
    ADD CONSTRAINT fks829uesiupi0lqb6ge6pgq06r FOREIGN KEY (campaign_id) REFERENCES client.campaign(id);

ALTER TABLE ONLY client.schedule_campaign_user
    ADD CONSTRAINT fksqwnh1xya0kfofn29ol3hngl6 FOREIGN KEY (schedule_campaign_settings_id) REFERENCES client.schedule_campaign_settings(id);

ALTER TABLE ONLY client.communicate_result
    ADD CONSTRAINT fktrm4h4fub4o6dbc53y17hxrtq FOREIGN KEY (client_id) REFERENCES client.clients(id);

ALTER TABLE ONLY client.poa_change_history
    ADD CONSTRAINT poa_change_history_poa_id_fkey FOREIGN KEY (poa_id) REFERENCES client.powers_of_attorney(id) DEFERRABLE;

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT powers_of_attorney_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT powers_of_attorney_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES client.contacts(id) DEFERRABLE;

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT powers_of_attorney_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES client.ref_document_types(id) DEFERRABLE;

ALTER TABLE ONLY client.powers_of_attorney
    ADD CONSTRAINT powers_of_attorney_poa_type_id_fkey FOREIGN KEY (poa_type_id) REFERENCES client.ref_poa_types(id) DEFERRABLE;

ALTER TABLE ONLY client.ref_departments
    ADD CONSTRAINT ref_departments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES client.ref_departments(id) DEFERRABLE;

ALTER TABLE ONLY client.related_contracts
    ADD CONSTRAINT related_contracts_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES client.contracts(id) DEFERRABLE;

ALTER TABLE ONLY client.related_contracts
    ADD CONSTRAINT related_contracts_related_contract_id_fkey FOREIGN KEY (related_contract_id) REFERENCES client.contracts(id) DEFERRABLE;

ALTER TABLE ONLY client.special_tariff_plans
    ADD CONSTRAINT special_tariff_plans_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.special_tariff_plans
    ADD CONSTRAINT special_tariff_plans_product_id_fkey FOREIGN KEY (product_id) REFERENCES client.products_services(id) DEFERRABLE;

ALTER TABLE ONLY client.subsidiaries
    ADD CONSTRAINT subsidiaries_city_region_id_fkey FOREIGN KEY (city_region_id) REFERENCES client.ref_cities_regions(id) DEFERRABLE;

ALTER TABLE ONLY client.subsidiaries
    ADD CONSTRAINT subsidiaries_parent_client_id_fkey FOREIGN KEY (parent_client_id) REFERENCES client.clients(id) DEFERRABLE;

ALTER TABLE ONLY client.tickets
    ADD CONSTRAINT tickets_client_id_fkey FOREIGN KEY (client_id) REFERENCES client.clients(id) DEFERRABLE;
