-- DROP SCHEMA doc;

CREATE SCHEMA doc AUTHORIZATION kcell_test_user;

-- DROP SEQUENCE doc.doc_history_id_seq;

CREATE SEQUENCE doc.doc_history_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE doc.doc_history_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE doc.doc_history_id_seq TO kcell_test_user;

-- DROP SEQUENCE doc.doc_template_id_seq;

CREATE SEQUENCE doc.doc_template_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE doc.doc_template_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE doc.doc_template_id_seq TO kcell_test_user;
-- doc.databasechangelog definition

-- Drop table

-- DROP TABLE doc.databasechangelog;

CREATE TABLE doc.databasechangelog ( id varchar(255) NOT NULL, author varchar(255) NOT NULL, filename varchar(255) NOT NULL, dateexecuted timestamp NOT NULL, orderexecuted int4 NOT NULL, exectype varchar(10) NOT NULL, md5sum varchar(35) NULL, description varchar(255) NULL, "comments" varchar(255) NULL, tag varchar(255) NULL, liquibase varchar(20) NULL, contexts varchar(255) NULL, labels varchar(255) NULL, deployment_id varchar(10) NULL);

-- Permissions

ALTER TABLE doc.databasechangelog OWNER TO kcell_test_user;
GRANT ALL ON TABLE doc.databasechangelog TO kcell_test_user;


-- doc.databasechangeloglock definition

-- Drop table

-- DROP TABLE doc.databasechangeloglock;

CREATE TABLE doc.databasechangeloglock ( id int4 NOT NULL, "locked" bool NOT NULL, lockgranted timestamp NULL, lockedby varchar(255) NULL, CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE doc.databasechangeloglock OWNER TO kcell_test_user;
GRANT ALL ON TABLE doc.databasechangeloglock TO kcell_test_user;


-- doc.doc_history definition

-- Drop table

-- DROP TABLE doc.doc_history;

CREATE TABLE doc.doc_history ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, doc_type varchar(255) NULL, created_date timestamp(6) NULL, iin varchar(255) NULL, minio_id uuid NULL, contract_number varchar(255) NULL, CONSTRAINT doc_history_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE doc.doc_history OWNER TO kcell_test_user;
GRANT ALL ON TABLE doc.doc_history TO kcell_test_user;


-- doc.doc_template definition

-- Drop table

-- DROP TABLE doc.doc_template;

CREATE TABLE doc.doc_template ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, doc_type varchar(255) NULL, file_name varchar(255) NULL, description varchar(255) NULL, created_date timestamp(6) NULL, minio_id uuid NULL, author varchar(255) NULL, template_name varchar(255) NULL, parameters jsonb NULL, is_active bool NULL, CONSTRAINT doc_template_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE doc.doc_template OWNER TO kcell_test_user;
GRANT ALL ON TABLE doc.doc_template TO kcell_test_user;




-- Permissions

GRANT ALL ON SCHEMA doc TO kcell_test_user;