-- DROP SCHEMA management;

CREATE SCHEMA management AUTHORIZATION kcell_test_user;

-- DROP SEQUENCE management.file_categories_seq;

CREATE SEQUENCE management.file_categories_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE management.file_categories_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE management.file_categories_seq TO kcell_test_user;

-- DROP SEQUENCE management.robot_id_seq;

CREATE SEQUENCE management.robot_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE management.robot_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE management.robot_id_seq TO kcell_test_user;

-- DROP SEQUENCE management.template_id_seq;

CREATE SEQUENCE management.template_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE management.template_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE management.template_id_seq TO kcell_test_user;

-- DROP SEQUENCE management.web_config_content_id_seq;

CREATE SEQUENCE management.web_config_content_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE management.web_config_content_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE management.web_config_content_id_seq TO kcell_test_user;

-- DROP SEQUENCE management.web_config_id_seq;

CREATE SEQUENCE management.web_config_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE management.web_config_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE management.web_config_id_seq TO kcell_test_user;
-- management.file_categories definition

-- Drop table

-- DROP TABLE management.file_categories;

CREATE TABLE management.file_categories ( id int8 NOT NULL, code varchar(255) NULL, value_en varchar(255) NULL, value_kz varchar(255) NULL, value_ru varchar(255) NULL, CONSTRAINT file_categories_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE management.file_categories OWNER TO kcell_test_user;
GRANT ALL ON TABLE management.file_categories TO kcell_test_user;


-- management.robot definition

-- Drop table

-- DROP TABLE management.robot;

CREATE TABLE management.robot ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "action" int2 NULL, consumer_count int4 NULL, "name" varchar(255) NULL, sip_password varchar(255) NULL, sip_user varchar(255) NULL, speech_recognition_max_duration int8 NULL, speech_recognition_sample_rate int8 NULL, speech_recognition_silence_counter int8 NULL, speech_recognition_silence_duration int8 NULL, speech_recognition_threshold int8 NULL, speech_without_audio_file bool NULL, task_id int8 NULL, yandex_speech_role_kz varchar(255) NULL, yandex_speech_role_ru varchar(255) NULL, yandex_speech_voice_kz varchar(255) NULL, yandex_speech_voice_ru varchar(255) NULL, status varchar(255) NULL, CONSTRAINT robot_action_check CHECK (((action >= 0) AND (action <= 3))), CONSTRAINT robot_pkey PRIMARY KEY (id), CONSTRAINT robot_status_check CHECK (((status)::text = ANY ((ARRAY['SEND_WAIT_RESPONSE'::character varying, 'SUCCESS_RESPONSE'::character varying, 'ERROR_RESPONSE'::character varying, 'REMOVED'::character varying])::text[]))));

-- Permissions

ALTER TABLE management.robot OWNER TO kcell_test_user;
GRANT ALL ON TABLE management.robot TO kcell_test_user;


-- management."template" definition

-- Drop table

-- DROP TABLE management."template";

CREATE TABLE management."template" ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at timestamp(6) NULL, created_by uuid NULL, deleted_at timestamp(6) NULL, updated_at timestamp(6) NULL, updated_by uuid NULL, channel varchar(255) NULL, last_modification_date timestamptz(6) NULL, "name" varchar(255) NULL, "text" text NULL, topic varchar(255) NULL, CONSTRAINT template_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE management."template" OWNER TO kcell_test_user;
GRANT ALL ON TABLE management."template" TO kcell_test_user;


-- management.web_config definition

-- Drop table

-- DROP TABLE management.web_config;

CREATE TABLE management.web_config ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at timestamp(6) NULL, created_by uuid NULL, deleted_at timestamp(6) NULL, updated_at timestamp(6) NULL, updated_by uuid NULL, code varchar(255) NULL, config jsonb NULL, description varchar(255) NULL, last_modification_date timestamp(6) NULL, property varchar(255) NULL, title varchar(255) NULL, "type" varchar(255) NULL, CONSTRAINT ukr5km4wnohbx8kth6wh1prspci UNIQUE (code), CONSTRAINT web_config_pkey PRIMARY KEY (id), CONSTRAINT web_config_type_check CHECK (((type)::text = ANY ((ARRAY['SIMPLE'::character varying, 'LIST'::character varying, 'REFERENCE'::character varying, 'TREELIKE'::character varying])::text[]))));

-- Permissions

ALTER TABLE management.web_config OWNER TO kcell_test_user;
GRANT ALL ON TABLE management.web_config TO kcell_test_user;


-- management.file_storage definition

-- Drop table

-- DROP TABLE management.file_storage;

CREATE TABLE management.file_storage ( id uuid NOT NULL, created_at timestamp(6) NULL, created_by uuid NULL, deleted_at timestamp(6) NULL, updated_at timestamp(6) NULL, updated_by uuid NULL, "comment" text NULL, file_size int8 NULL, file_type varchar(255) NULL, filename varchar(255) NULL, is_deleted bool NULL, mime_type varchar(255) NULL, object_id uuid NULL, object_type varchar(255) NULL, stored_name varchar(255) NULL, uploaded_by_name varchar(255) NULL, category_id int8 NULL, CONSTRAINT file_storage_pkey PRIMARY KEY (id), CONSTRAINT fkken9fvy1fri57ivq4n7o2b13u FOREIGN KEY (category_id) REFERENCES management.file_categories(id));

-- Permissions

ALTER TABLE management.file_storage OWNER TO kcell_test_user;
GRANT ALL ON TABLE management.file_storage TO kcell_test_user;


-- management.web_config_content definition

-- Drop table

-- DROP TABLE management.web_config_content;

CREATE TABLE management.web_config_content ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at timestamp(6) NULL, created_by uuid NULL, deleted_at timestamp(6) NULL, updated_at timestamp(6) NULL, updated_by uuid NULL, "key" varchar(255) NULL, reference_config jsonb NULL, value varchar(255) NULL, value_en varchar(255) NULL, value_kz varchar(255) NULL, value_ru varchar(255) NULL, config_id int8 NULL, CONSTRAINT web_config_content_pkey PRIMARY KEY (id), CONSTRAINT fkgdfvmsy2q8n4k13xakux22n3a FOREIGN KEY (config_id) REFERENCES management.web_config(id));

-- Permissions

ALTER TABLE management.web_config_content OWNER TO kcell_test_user;
GRANT ALL ON TABLE management.web_config_content TO kcell_test_user;




-- Permissions

GRANT ALL ON SCHEMA management TO kcell_test_user;