-- DROP SCHEMA message;

CREATE SCHEMA message AUTHORIZATION kcell_test_user;

-- DROP SEQUENCE message.mailing_client_id_seq;

CREATE SEQUENCE message.mailing_client_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE message.mailing_client_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE message.mailing_client_id_seq TO kcell_test_user;

-- DROP SEQUENCE message.mailing_id_seq;

CREATE SEQUENCE message.mailing_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE message.mailing_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE message.mailing_id_seq TO kcell_test_user;

-- DROP SEQUENCE message.message_history_id_seq;

CREATE SEQUENCE message.message_history_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE message.message_history_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE message.message_history_id_seq TO kcell_test_user;

-- DROP SEQUENCE message.template_id_seq;

CREATE SEQUENCE message.template_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE message.template_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE message.template_id_seq TO kcell_test_user;
-- message.databasechangelog definition

-- Drop table

-- DROP TABLE message.databasechangelog;

CREATE TABLE message.databasechangelog ( id varchar(255) NOT NULL, author varchar(255) NOT NULL, filename varchar(255) NOT NULL, dateexecuted timestamp NOT NULL, orderexecuted int4 NOT NULL, exectype varchar(10) NOT NULL, md5sum varchar(35) NULL, description varchar(255) NULL, "comments" varchar(255) NULL, tag varchar(255) NULL, liquibase varchar(20) NULL, contexts varchar(255) NULL, labels varchar(255) NULL, deployment_id varchar(10) NULL);

-- Permissions

ALTER TABLE message.databasechangelog OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.databasechangelog TO kcell_test_user;


-- message.databasechangeloglock definition

-- Drop table

-- DROP TABLE message.databasechangeloglock;

CREATE TABLE message.databasechangeloglock ( id int4 NOT NULL, "locked" bool NOT NULL, lockgranted timestamp NULL, lockedby varchar(255) NULL, CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE message.databasechangeloglock OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.databasechangeloglock TO kcell_test_user;


-- message.mailing definition

-- Drop table

-- DROP TABLE message.mailing;

CREATE TABLE message.mailing ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, campaign_id int8 NULL, campaign_name varchar(255) NULL, channel varchar(255) NOT NULL, client_count int8 NULL, end_time time(6) NULL, "name" varchar(255) NULL, start_time time(6) NULL, status varchar(255) NULL, template_id int8 NULL, template_name varchar(255) NULL, CONSTRAINT mailing_channel_check CHECK (((channel)::text = ANY ((ARRAY['SMS'::character varying, 'WHATSAPP'::character varying, 'EMAIL'::character varying])::text[]))), CONSTRAINT mailing_pkey PRIMARY KEY (id), CONSTRAINT mailing_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'PAUSED'::character varying, 'CANCELLED'::character varying, 'DRAFT'::character varying, 'COMPLETED'::character varying])::text[]))));

-- Permissions

ALTER TABLE message.mailing OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.mailing TO kcell_test_user;


-- message.message_history definition

-- Drop table

-- DROP TABLE message.message_history;

CREATE TABLE message.message_history ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, subject varchar(255) NULL, message varchar(255) NULL, status varchar(255) NULL, channel varchar(255) NULL, mailing_type varchar(255) NULL, send_date timestamp NULL, status_code int4 NULL, status_desc varchar(255) NULL, msg_extern_id varchar(255) NULL, recipient varchar(255) NULL, contract_number varchar(255) NULL, iin varchar(255) NULL, topic varchar(255) NULL, CONSTRAINT pk_messagehistory PRIMARY KEY (id));

-- Permissions

ALTER TABLE message.message_history OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.message_history TO kcell_test_user;


-- message."template" definition

-- Drop table

-- DROP TABLE message."template";

CREATE TABLE message."template" ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, channel varchar(255) NULL, last_modification_date timestamptz(6) NULL, "name" varchar(255) NULL, "text" text NULL, topic varchar(255) NULL, CONSTRAINT template_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE message."template" OWNER TO kcell_test_user;
GRANT ALL ON TABLE message."template" TO kcell_test_user;


-- message.mailing_client definition

-- Drop table

-- DROP TABLE message.mailing_client;

CREATE TABLE message.mailing_client ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, iin varchar(12) NOT NULL, is_processed bool NOT NULL, processing_result varchar(255) NULL, mailing_id int8 NOT NULL, CONSTRAINT mailing_client_pkey PRIMARY KEY (id), CONSTRAINT fkd4b96hrh3rrnja2f3c1jmactu FOREIGN KEY (mailing_id) REFERENCES message.mailing(id));

-- Permissions

ALTER TABLE message.mailing_client OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.mailing_client TO kcell_test_user;


-- message.mailing_days_of_week definition

-- Drop table

-- DROP TABLE message.mailing_days_of_week;

CREATE TABLE message.mailing_days_of_week ( mailing_id int8 NOT NULL, day_of_week varchar(255) NULL, CONSTRAINT mailing_days_of_week_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))), CONSTRAINT fkdavyj4auawseefhsmhko3sgwy FOREIGN KEY (mailing_id) REFERENCES message.mailing(id));

-- Permissions

ALTER TABLE message.mailing_days_of_week OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.mailing_days_of_week TO kcell_test_user;


-- message.message_metadata definition

-- Drop table

-- DROP TABLE message.message_metadata;

CREATE TABLE message.message_metadata ( message_id int8 NOT NULL, meta_key varchar(255) NOT NULL, meta_value varchar(255) NULL, CONSTRAINT pk_message_metadata PRIMARY KEY (message_id, meta_key), CONSTRAINT fk_metadata_message_history FOREIGN KEY (message_id) REFERENCES message.message_history(id));

-- Permissions

ALTER TABLE message.message_metadata OWNER TO kcell_test_user;
GRANT ALL ON TABLE message.message_metadata TO kcell_test_user;




-- Permissions

GRANT ALL ON SCHEMA message TO kcell_test_user;