-- DROP SCHEMA notification;

CREATE SCHEMA notification AUTHORIZATION kcell_test_user;

-- DROP SEQUENCE notification.internal_notifications_id_seq;

CREATE SEQUENCE notification.internal_notifications_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE notification.internal_notifications_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE notification.internal_notifications_id_seq TO kcell_test_user;

-- DROP SEQUENCE notification.w_notifications_id_seq;

CREATE SEQUENCE notification.w_notifications_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE notification.w_notifications_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE notification.w_notifications_id_seq TO kcell_test_user;

-- DROP SEQUENCE notification.whatsapp_history_seq;

CREATE SEQUENCE notification.whatsapp_history_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE notification.whatsapp_history_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE notification.whatsapp_history_seq TO kcell_test_user;
-- notification.databasechangelog definition

-- Drop table

-- DROP TABLE notification.databasechangelog;

CREATE TABLE notification.databasechangelog ( id varchar(255) NOT NULL, author varchar(255) NOT NULL, filename varchar(255) NOT NULL, dateexecuted timestamp NOT NULL, orderexecuted int4 NOT NULL, exectype varchar(10) NOT NULL, md5sum varchar(35) NULL, description varchar(255) NULL, "comments" varchar(255) NULL, tag varchar(255) NULL, liquibase varchar(20) NULL, contexts varchar(255) NULL, labels varchar(255) NULL, deployment_id varchar(10) NULL);

-- Permissions

ALTER TABLE notification.databasechangelog OWNER TO kcell_test_user;
GRANT ALL ON TABLE notification.databasechangelog TO kcell_test_user;


-- notification.databasechangeloglock definition

-- Drop table

-- DROP TABLE notification.databasechangeloglock;

CREATE TABLE notification.databasechangeloglock ( id int4 NOT NULL, "locked" bool NOT NULL, lockgranted timestamp NULL, lockedby varchar(255) NULL, CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE notification.databasechangeloglock OWNER TO kcell_test_user;
GRANT ALL ON TABLE notification.databasechangeloglock TO kcell_test_user;


-- notification.internal_notifications definition

-- Drop table

-- DROP TABLE notification.internal_notifications;

CREATE TABLE notification.internal_notifications ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, action_url varchar(255) NULL, created_at timestamptz(6) NULL, message varchar(255) NULL, receiver_collection varchar(255) NULL, receiver_dep_id int8 NULL, receiver_id uuid NULL, receiver_role varchar(255) NULL, receiver_srv_dep_code varchar(255) NULL, status varchar(255) NULL, title varchar(255) NULL, "type" varchar(255) NULL, CONSTRAINT internal_notifications_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE notification.internal_notifications OWNER TO kcell_test_user;
GRANT ALL ON TABLE notification.internal_notifications TO kcell_test_user;


-- notification.w_notifications definition

-- Drop table

-- DROP TABLE notification.w_notifications;

CREATE TABLE notification.w_notifications ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, count int4 NULL, create_date timestamp(6) NULL, phone_number varchar(255) NULL, CONSTRAINT w_notifications_pkey PRIMARY KEY (id));
CREATE INDEX ws_notify_indexes ON notification.w_notifications USING btree (phone_number);

-- Permissions

ALTER TABLE notification.w_notifications OWNER TO kcell_test_user;
GRANT ALL ON TABLE notification.w_notifications TO kcell_test_user;


-- notification.whatsapp_history definition

-- Drop table

-- DROP TABLE notification.whatsapp_history;

CREATE TABLE notification.whatsapp_history ( id int8 NOT NULL, client_id varchar(255) NULL, delivery_date timestamptz(6) NULL, is_read bool NULL, phone_number varchar(255) NULL, send_date timestamptz(6) NULL, sender varchar(255) NULL, status_code int4 NOT NULL, "text" varchar(255) NULL, CONSTRAINT whatsapp_history_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE notification.whatsapp_history OWNER TO kcell_test_user;
GRANT ALL ON TABLE notification.whatsapp_history TO kcell_test_user;




-- Permissions

GRANT ALL ON SCHEMA notification TO kcell_test_user;