-- DROP SCHEMA users;

CREATE SCHEMA users AUTHORIZATION kcell_test_user;

-- DROP SEQUENCE users.api_actions_id_seq;

CREATE SEQUENCE users.api_actions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.api_actions_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.api_actions_id_seq TO kcell_test_user;

-- DROP SEQUENCE users.api_id_seq;

CREATE SEQUENCE users.api_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.api_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.api_id_seq TO kcell_test_user;

-- DROP SEQUENCE users.dashboard_attributes_seq;

CREATE SEQUENCE users.dashboard_attributes_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.dashboard_attributes_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.dashboard_attributes_seq TO kcell_test_user;

-- DROP SEQUENCE users.dashboard_role_seq;

CREATE SEQUENCE users.dashboard_role_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.dashboard_role_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.dashboard_role_seq TO kcell_test_user;

-- DROP SEQUENCE users.dashboards_seq;

CREATE SEQUENCE users.dashboards_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.dashboards_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.dashboards_seq TO kcell_test_user;

-- DROP SEQUENCE users.organizational_units_id_seq;

CREATE SEQUENCE users.organizational_units_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.organizational_units_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.organizational_units_id_seq TO kcell_test_user;

-- DROP SEQUENCE users.role_id_seq;

CREATE SEQUENCE users.role_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.role_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.role_id_seq TO kcell_test_user;

-- DROP SEQUENCE users.role_seq;

CREATE SEQUENCE users.role_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.role_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.role_seq TO kcell_test_user;

-- DROP SEQUENCE users.token_seq;

CREATE SEQUENCE users.token_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.token_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.token_seq TO kcell_test_user;

-- DROP SEQUENCE users.user_status_log_id_seq;

CREATE SEQUENCE users.user_status_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.user_status_log_id_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.user_status_log_id_seq TO kcell_test_user;

-- DROP SEQUENCE users.users_seq;

CREATE SEQUENCE users.users_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE users.users_seq OWNER TO kcell_test_user;
GRANT ALL ON SEQUENCE users.users_seq TO kcell_test_user;
-- users.api definition

-- Drop table

-- DROP TABLE users.api;

CREATE TABLE users.api ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at timestamptz(6) NULL, created_by uuid NULL, deleted_at timestamptz(6) NULL, updated_at timestamptz(6) NULL, updated_by uuid NULL, code varchar(255) NULL, description varchar(255) NULL, root_path varchar(255) NULL, parent_code varchar(255) NULL, "type" varchar(255) DEFAULT 'PERMISSION'::character varying NOT NULL, CONSTRAINT api_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE users.api OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.api TO kcell_test_user;


-- users.dashboards definition

-- Drop table

-- DROP TABLE users.dashboards;

CREATE TABLE users.dashboards ( id int8 NOT NULL, "key" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, status varchar(255) NULL, CONSTRAINT dashboards_pkey PRIMARY KEY (id), CONSTRAINT dashboards_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))), CONSTRAINT ukdv3a93mpeymau84qkdkx5jeif UNIQUE (key));

-- Permissions

ALTER TABLE users.dashboards OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.dashboards TO kcell_test_user;


-- users.databasechangelog definition

-- Drop table

-- DROP TABLE users.databasechangelog;

CREATE TABLE users.databasechangelog ( id varchar(255) NOT NULL, author varchar(255) NOT NULL, filename varchar(255) NOT NULL, dateexecuted timestamp NOT NULL, orderexecuted int4 NOT NULL, exectype varchar(10) NOT NULL, md5sum varchar(35) NULL, description varchar(255) NULL, "comments" varchar(255) NULL, tag varchar(255) NULL, liquibase varchar(20) NULL, contexts varchar(255) NULL, labels varchar(255) NULL, deployment_id varchar(10) NULL);

-- Permissions

ALTER TABLE users.databasechangelog OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.databasechangelog TO kcell_test_user;


-- users.databasechangeloglock definition

-- Drop table

-- DROP TABLE users.databasechangeloglock;

CREATE TABLE users.databasechangeloglock ( id int4 NOT NULL, "locked" bool NOT NULL, lockgranted timestamp NULL, lockedby varchar(255) NULL, CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE users.databasechangeloglock OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.databasechangeloglock TO kcell_test_user;


-- users."role" definition

-- Drop table

-- DROP TABLE users."role";

CREATE TABLE users."role" ( id bigserial NOT NULL, created_at timestamptz(6) NULL, created_by uuid NULL, deleted_at timestamptz(6) NULL, updated_at timestamptz(6) NULL, updated_by uuid NULL, code varchar(255) NULL, description varchar(255) NULL, CONSTRAINT role_pkey PRIMARY KEY (id), CONSTRAINT uk_role_code UNIQUE (code));

-- Permissions

ALTER TABLE users."role" OWNER TO kcell_test_user;
GRANT ALL ON TABLE users."role" TO kcell_test_user;


-- users.api_actions definition

-- Drop table

-- DROP TABLE users.api_actions;

CREATE TABLE users.api_actions ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, code varchar(100) NOT NULL, description varchar(255) NOT NULL, api_id int8 NOT NULL, CONSTRAINT api_actions_pkey PRIMARY KEY (id), CONSTRAINT fk7hu4k6x7it1ukrnqiu58lylw5 FOREIGN KEY (api_id) REFERENCES users.api(id));

-- Permissions

ALTER TABLE users.api_actions OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.api_actions TO kcell_test_user;


-- users.dashboard_attributes definition

-- Drop table

-- DROP TABLE users.dashboard_attributes;

CREATE TABLE users.dashboard_attributes ( id int8 NOT NULL, difference float8 NULL, "name" varchar(255) NOT NULL, "type" varchar(255) NOT NULL, unit varchar(255) NULL, value float8 NOT NULL, dashboard_id int8 NOT NULL, CONSTRAINT dashboard_attributes_pkey PRIMARY KEY (id), CONSTRAINT fkexk2tu992jl6oo9683sm7jvpl FOREIGN KEY (dashboard_id) REFERENCES users.dashboards(id));

-- Permissions

ALTER TABLE users.dashboard_attributes OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.dashboard_attributes TO kcell_test_user;


-- users.dashboard_role definition

-- Drop table

-- DROP TABLE users.dashboard_role;

CREATE TABLE users.dashboard_role ( id int8 NOT NULL, dashboard_id int8 NOT NULL, role_id int8 NOT NULL, CONSTRAINT dashboard_role_pkey PRIMARY KEY (id), CONSTRAINT fkbe7m0djpnvbgqnkqjpcp3x3ed FOREIGN KEY (dashboard_id) REFERENCES users.dashboards(id), CONSTRAINT fkj9aiq562tfth04c257l3c8p1c FOREIGN KEY (role_id) REFERENCES users."role"(id));

-- Permissions

ALTER TABLE users.dashboard_role OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.dashboard_role TO kcell_test_user;


-- users.organizational_units definition

-- Drop table

-- DROP TABLE users.organizational_units;

CREATE TABLE users.organizational_units ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, code varchar(20) NOT NULL, created_at timestamp(6) NULL, deleted_at timestamp(6) NULL, "level" int4 NOT NULL, "name" varchar(200) NOT NULL, updated_at timestamp(6) NULL, parent_id int8 NULL, created_by uuid NULL, updated_by uuid NULL, CONSTRAINT organizational_units_pkey PRIMARY KEY (id), CONSTRAINT fk2cm7evuvvhuxepsnn0xneabbc FOREIGN KEY (parent_id) REFERENCES users.organizational_units(id));

-- Permissions

ALTER TABLE users.organizational_units OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.organizational_units TO kcell_test_user;


-- users.role_permissions definition

-- Drop table

-- DROP TABLE users.role_permissions;

CREATE TABLE users.role_permissions ( api_id int8 NOT NULL, role_id int8 NOT NULL, "create" bool NULL, "delete" bool NULL, "read" bool NULL, "update" bool NULL, CONSTRAINT role_permissions_pkey PRIMARY KEY (api_id, role_id), CONSTRAINT fkdm26jx9dvq2y6mct96rd4p2yl FOREIGN KEY (api_id) REFERENCES users.api(id), CONSTRAINT fklodb7xh4a2xjv39gc3lsop95n FOREIGN KEY (role_id) REFERENCES users."role"(id));

-- Permissions

ALTER TABLE users.role_permissions OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.role_permissions TO kcell_test_user;


-- users.role_subordination definition

-- Drop table

-- DROP TABLE users.role_subordination;

CREATE TABLE users.role_subordination ( id uuid NOT NULL, created_at timestamptz(6) NULL, created_by uuid NULL, deleted_at timestamptz(6) NULL, updated_at timestamptz(6) NULL, updated_by uuid NULL, id_role_child int8 NOT NULL, id_role_parent int8 NOT NULL, CONSTRAINT role_subordination_pkey PRIMARY KEY (id), CONSTRAINT fk_role_sub_child FOREIGN KEY (id_role_child) REFERENCES users."role"(id), CONSTRAINT fk_role_sub_parent FOREIGN KEY (id_role_parent) REFERENCES users."role"(id));

-- Permissions

ALTER TABLE users.role_subordination OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.role_subordination TO kcell_test_user;


-- users.users definition

-- Drop table

-- DROP TABLE users.users;

CREATE TABLE users.users ( id bigserial NOT NULL, created_at timestamptz(6) NULL, created_by uuid NULL, deleted_at timestamptz(6) NULL, updated_at timestamptz(6) NULL, updated_by uuid NULL, atc_password varchar(255) NULL, avatar_base64 oid NULL, avatar_uuid varchar(255) NULL, collection varchar(255) NULL, description varchar(255) NULL, email varchar(255) NULL, fio varchar(255) NULL, keycloak_id uuid NULL, "password" varchar(255) NULL, phone varchar(255) NULL, status varchar(255) NULL, "structure" varchar(255) NULL, username varchar(255) NULL, organization_id int8 NULL, role_id int8 NULL, "module" varchar(255) NULL, org_contains_all_children bool DEFAULT false NOT NULL, CONSTRAINT uk_users_username UNIQUE (username), CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username), CONSTRAINT users_pkey PRIMARY KEY (id), CONSTRAINT fk4qu1gr772nnf6ve5af002rwya FOREIGN KEY (role_id) REFERENCES users."role"(id), CONSTRAINT fkmo8cjl5wbf953yvgy7hmlhp7l FOREIGN KEY (organization_id) REFERENCES users.organizational_units(id));

-- Permissions

ALTER TABLE users.users OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.users TO kcell_test_user;


-- users.role_permission_actions definition

-- Drop table

-- DROP TABLE users.role_permission_actions;

CREATE TABLE users.role_permission_actions ( action_code varchar(100) NOT NULL, api_id int8 NOT NULL, role_id int8 NOT NULL, enabled bool NULL, CONSTRAINT role_permission_actions_pkey PRIMARY KEY (action_code, api_id, role_id), CONSTRAINT fkj1l59vq3r7wixxl871kyfyivb FOREIGN KEY (api_id,role_id) REFERENCES users.role_permissions(api_id,role_id));

-- Permissions

ALTER TABLE users.role_permission_actions OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.role_permission_actions TO kcell_test_user;


-- users."token" definition

-- Drop table

-- DROP TABLE users."token";

CREATE TABLE users."token" ( id int8 NOT NULL, expiry_date timestamptz(6) NULL, "token" varchar(255) NULL, user_id int8 NULL, CONSTRAINT token_pkey PRIMARY KEY (id), CONSTRAINT ukg7im3j7f0g31yhl6qco2iboy5 UNIQUE (user_id), CONSTRAINT fkj8rfw4x0wjjyibfqq566j4qng FOREIGN KEY (user_id) REFERENCES users.users(id));

-- Permissions

ALTER TABLE users."token" OWNER TO kcell_test_user;
GRANT ALL ON TABLE users."token" TO kcell_test_user;


-- users.user_organizational_units definition

-- Drop table

-- DROP TABLE users.user_organizational_units;

CREATE TABLE users.user_organizational_units ( user_id int8 NOT NULL, organizational_unit_id int8 NOT NULL, CONSTRAINT fk_user_organizational_units_organizational_units FOREIGN KEY (organizational_unit_id) REFERENCES users.organizational_units(id), CONSTRAINT fk_user_organizational_units_users FOREIGN KEY (user_id) REFERENCES users.users(id));

-- Permissions

ALTER TABLE users.user_organizational_units OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.user_organizational_units TO kcell_test_user;


-- users.user_srv_dep_codes definition

-- Drop table

-- DROP TABLE users.user_srv_dep_codes;

CREATE TABLE users.user_srv_dep_codes ( user_id int8 NOT NULL, srv_dep_code varchar(255) NULL, CONSTRAINT fk_user_srv_dep_codes_user_id FOREIGN KEY (user_id) REFERENCES users.users(id) ON DELETE CASCADE);

-- Permissions

ALTER TABLE users.user_srv_dep_codes OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.user_srv_dep_codes TO kcell_test_user;


-- users.user_status_log definition

-- Drop table

-- DROP TABLE users.user_status_log;

CREATE TABLE users.user_status_log ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, end_time timestamptz(6) NULL, start_time timestamptz(6) NOT NULL, status varchar(255) NOT NULL, user_id int8 NOT NULL, CONSTRAINT user_status_log_pkey PRIMARY KEY (id), CONSTRAINT fkflec53r1sfnr6ywsmrdadp05e FOREIGN KEY (user_id) REFERENCES users.users(id));

-- Permissions

ALTER TABLE users.user_status_log OWNER TO kcell_test_user;
GRANT ALL ON TABLE users.user_status_log TO kcell_test_user;




-- Permissions

GRANT ALL ON SCHEMA users TO kcell_test_user;